name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js (version 18)
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Установите Node.js 18 или выше

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        npm install
        npx playwright install  # Устанавливаем необходимые зависимости Playwright

    - name: Give Playwright permission to execute
      run: chmod +x ./node_modules/.bin/playwright  # Устанавливаем права на выполнение

    - name: Run Playwright tests
      run: npx playwright test
