name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  install-dependencies:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install system dependencies for Playwright
      run: |
        sudo apt-get update
        sudo apt-get install -y 

    - name: Install dependencies
      run: |
        npm install

  test:
    needs: install-dependencies
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm install

    - name: Grant execute permissions to Playwright
      run: |
        chmod +x ./node_modules/.bin/playwright

    - name: Run Playwright tests
      run: |
        npx playwright install --with-deps
        npx playwright test --reporter=line,allure-playwright
      env:
        ALLURE_RESULTS_DIR: allure-results

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
      if: always()  # Этот шаг выполнится всегда, даже если тесты не прошли.

    - name: Check Allure results directory
      run: ls -l allure-results
      if: always()  # Этот шаг выполнится всегда.

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
      if: always()  

    - name: Ensure allure-report folder exists
      run: |
        if [ ! -d "allure-report" ]; then
          echo "allure-report folder does not exist, creating..."
          mkdir allure-report
        fi
      if: always()  # Этот шаг выполнится всегда.

    - name: Clear previous report contents
      run: |
        rm -rf allure-report/*
        echo "Old Allure report files removed"
      if: always()  # Этот шаг выполнится всегда.

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@v1
      with:
        allure_results: allure-results
        allure_report: allure-report
      if: always()  # Этот шаг также выполнится всегда.

    - name: Add Allure report files to git
      run: |
        git add allure-report/*
        git commit -m "Add Allure report"
        git push origin gh-pages
      if: always()  # Этот шаг выполнится всегда.

    - name: Deploy Allure Report to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: allure-report
        clean: true  # Важно: мы используем clean: true для очистки старых данных на GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: always()  # Этот шаг выполнится всегда.
