name: Playwright Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Убедитесь, что версия Node.js >= 18

      - name: Install dependencies
        run: |
          npm ci  # Это гарантирует установку зависимостей в соответствии с package-lock.json

      - name: Install Playwright dependencies
        run: npx playwright install  # Устанавливает браузеры и другие зависимости Playwright

      - name: Run Playwright tests
        run: npx playwright test  # Запускает тесты Playwright
